name: RowMissiles
version: '${project.version}'
main: me.rownox.rowmissiles.RowMissiles
api-version: 1.19
commands:
  missiles:
    usage: "/missiles"
    description: "Access all of the missiles."
    aliases:
      - nukes
      - bombs